BaseURL = "https://indigodesigns.com"
languageCode = "en-us"
title = "Indigo Designs"
theme = "indigodesigns"

relativeURLS = true
enableEmoji = true
enableGitInfo = true

#sectionPagesMenu = "main"

#googleAnalytics = "UA-114931239-3"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/bootstrap.bundle.min.js"

[[module.mounts]]
source = "node_modules/bootstrap-icons/font/fonts"
target = "static/css/fonts"

[[module.mounts]]
source = "node_modules/bootstrap-icons/bootstrap-icons.svg"
target = "static/images/bootstrap-icons.svg"

[[module.mounts]]
source = "node_modules/bootstrap-icons/icons"
target = "static/images/icons"




