description = "Indigo Designs - Designs That Care!"

catchphrase = "We do the heavy lifting."
copyright = "Copyright &copy; 2022 Indigo Designs. All Rights Reserved."
crafted_email_url = "mailto:Claycle <05_cod_chimp@icloud.com>?subject=Comment%20on%20Indigo%20Designs"


logo = "/images/logo.svg"
logo_square = "/images/logo-square.svg"
logo_icon = "/images/logo-icon.svg"
logo_icon_inverted = "/images/logo-icon-inverted.svg"

[homepage_meta_tags]
meta_description = "Indigo Designs - Designs That Care"
meta_keywords = "texas,dallas,home,house,interior,design,consulting,renovations,redesign,improvement"
meta_og_title = "Indigo Designs"
meta_og_type = "website"
meta_og_url = "https://indigodesigns.com"
meta_og_image = ""
meta_og_description = "Indigo Designs - Designs That Care"
meta_twitter_card = "summary_large_image"
meta_twitter_site = "@indigodesigns"
meta_twitter_creator = "@indigodesigns"

[address]
street = "1234 Main Street"
city = "Dallas"
state = "TX"
zipcode = "12345"
phone = "555-555-5555"

[snippets]
dividerclasses = "col col-12 bg-dark pb-2"  # for example, <div class="{{ $.Param "snippets.dividerclasses" }}"></div>

# The following can be overridden per page cascade
[cascade.cover]
url = "https://picsum.photos/1050/450"
url1x1 = "https://picsum.photos/450"
content = """
<div class='d-none d-md-block w-100'><img src='/images/logo.svg' class='w-75'></div>
<div class='d-block d-md-none w-100'><img src='/images/logo-square.svg'  class='w-50'></div>
"""
heroic = false
thin = false
hidden = false

