copyright = "Copyright &copy; 2022 Indigo Designs. All Rights Reserved."
crafted_email_url = "mailto:Clay <05_cod_chimp@icloud.com>?subject=Comment%20on%20North%20Texas%20Aikido"

logo = "/images/logo.svg"
logo_square = "/images/logo-square.svg"
logo_icon = "/images/logo-icon.svg"
logo_icon_inverted = "/images/logo-icon-inverted.svg"

[address]
street = "1234 Main Street"
city = "Dallas"
state = "TX"
zipcode = "12345"
phone = "555-555-5555"

# The following can be overridden per page cascade
[cascade]
    cover = "https://picsum.photos/1050/450"
    cover_square = "https://picsum.photos/450"
    cover_content = "<div class='shadow-sm'><img src='/images/logo.svg' class='w-100 d-block'></div>"
    cover_content_square = "<div class='shadow-sm'><img src='/images/logo-square.svg' class='w-100 d-block'></div>"

