catchphrase = "We do the heavy lifting."
copyright = "Copyright &copy; 2022 Indigo Designs. All Rights Reserved."
crafted_email_url = "mailto:Clay <05_cod_chimp@icloud.com>?subject=Comment%20on%20North%20Texas%20Aikido"


logo = "/images/logo.svg"
logo_square = "/images/logo-square.svg"
logo_icon = "/images/logo-icon.svg"
logo_icon_inverted = "/images/logo-icon-inverted.svg"

[address]
street = "1234 Main Street"
city = "Dallas"
state = "TX"
zipcode = "12345"
phone = "555-555-5555"

[snippets]
dividerclasses = "col col-12 bg-dark pb-2"  # for example, <div class="{{ $.Param "snippets.dividerclasses" }}"></div>

# The following can be overridden per page cascade
[cascade.cover]
url = "https://picsum.photos/1050/450"
url1x1 = "https://picsum.photos/450"
content = """
<div class='d-none d-md-block w-100'><img src='/images/logo.svg' class='w-75'></div>
<div class='d-block d-md-none w-100'><img src='/images/logo-square.svg'  class='w-50'></div>
"""
heroic = false
thin = false
hidden = false

